/** Fragment + vertex shaders from Claude Design Event Horizon.dc.html — do not alter. */

export const VERT = 'attribute vec2 aPos; void main(){ gl_Position = vec4(aPos, 0.0, 1.0); }'

export const FRAG = [
  'precision highp float;',
  'uniform vec2 uRes, uMouse, uHot;',
  'uniform float uT, uAz, uEl, uZoom, uGlow, uGrain, uDense, uFlash, uSteps, uFlare, uFlareA, uHotI, uStars;',
  'float hash(vec2 p){ return fract(sin(dot(p, vec2(41.31, 289.07))) * 43758.5453); }',
  'float vnoise(vec2 p){',
  '  vec2 i = floor(p); vec2 fq = fract(p); fq = fq * fq * (3.0 - 2.0 * fq);',
  '  float a = hash(i), b = hash(i + vec2(1.0, 0.0)), c = hash(i + vec2(0.0, 1.0)), d = hash(i + vec2(1.0, 1.0));',
  '  return mix(mix(a, b, fq.x), mix(c, d, fq.x), fq.y);',
  '}',
  'float fbm(vec2 p){ return 0.55 * vnoise(p) + 0.28 * vnoise(p * 2.17 + 11.3) + 0.17 * vnoise(p * 4.31 + 41.7); }',
  'vec3 starLayer(vec3 d, vec2 dens, float pw, float amp, float sd){',
  '  float lat = asin(clamp(d.y, -1.0, 1.0));',
  '  vec2 sph = vec2(atan(d.z, d.x) * 0.1591 + 0.5, lat * 0.3183 + 0.5);',
  '  vec2 g = sph * dens;',
  '  vec2 c = floor(g); vec2 fr = fract(g) - 0.5;',
  '  vec2 jit = vec2(hash(c + sd + 7.1), hash(c + sd + 13.3)) - 0.5;',
  '  vec2 dv = fr - jit * 0.68;',
  '  float ax = (6.2832 / dens.x) * max(0.15, cos(lat));',
  '  float ay = 3.1416 / dens.y;',
  '  float ang = length(vec2(dv.x * ax, dv.y * ay));',
  '  float h = hash(c + sd);',
  '  float mag = pow(hash(c + sd + 3.7), pw);',
  '  float sz = 0.0013 + mag * 0.0022;',
  '  float core = exp(-pow(ang / sz, 2.0));',
  '  float halo = exp(-pow(ang / (sz * 5.0), 2.0)) * 0.1;',
  '  float tw = 0.78 + 0.22 * sin(uT * 0.9 + h * 44.0);',
  '  vec3 tint = mix(vec3(0.76, 0.83, 1.0), vec3(1.0, 0.95, 0.87), hash(c + sd + 21.7));',
  '  return tint * mag * (core + halo) * tw * amp;',
  '}',
  'vec3 stars(vec3 d){',
  '  return starLayer(d, vec2(260.0, 150.0), 22.0, 1.5, 0.0)',
  '       + starLayer(d, vec2(110.0, 64.0), 36.0, 3.4, 37.0);',
  '}',
  'void main(){',
  '  vec2 uv = (gl_FragCoord.xy - 0.5 * uRes) / uRes.y;',
  '  float tanHalf = 0.3 * uZoom;',
  '  float D = 30.0;',
  '  vec3 camPos = vec3(sin(uAz) * cos(uEl), sin(uEl), cos(uAz) * cos(uEl)) * D;',
  '  vec3 fw = normalize(-camPos);',
  '  vec3 rt = normalize(cross(vec3(0.0, 1.0, 0.0), fw));',
  '  vec3 up = cross(fw, rt);',
  '  vec2 sc = uv * 2.0 * tanHalf;',
  '  if (uMouse.x < 900.0) {',
  '    vec2 dm = uv - uMouse; float lm = length(dm);',
  '    sc += normalize(dm + 1e-5) * exp(-lm * 5.0) * 0.05;',
  '  }',
  '  vec3 dir = normalize(fw + rt * sc.x + up * sc.y);',
  '  float dith = hash(gl_FragCoord.xy * 1.37 + fract(uT) * 19.0);',
  '  vec3 col = vec3(0.0); float trans = 1.0; bool caught = false;',
  '  float bimp = length(cross(camPos, dir));',
  '  float pd = dot(camPos, dir);',
  '  float disc = pd * pd - (dot(camPos, camPos) - 256.0);',
  '  vec3 outDir = dir;',
  '  if (disc > 0.0) {',
  '    vec3 pos = camPos + dir * max(-pd - sqrt(disc), 0.0);',
  '    vec3 hv = cross(pos, dir); float h2 = dot(hv, hv);',
  '    float prevY = pos.y;',
  '    for (int i = 0; i < 120; i++) {',
  '      if (float(i) >= uSteps || trans < 0.02) break;',
  '      float r = length(pos);',
  '      if (r > 17.0) break;',
  '      float nearPlane = 1.0 - smoothstep(0.5, 2.2, abs(pos.y));',
  '      float dt = clamp(r * 0.05, 0.018, 0.55) * mix(1.0, 0.34, nearPlane) * (1.0 + smoothstep(7.0, 16.0, r) * 1.8) * (1.0 + (dith - 0.5) * 0.22 * smoothstep(2.4, 7.0, r));',
  '      vec3 acc = -1.5 * h2 * pos / pow(r, 5.0);',
  '      vec3 nd = dir + acc * dt;',
  '      vec3 np = pos + nd * dt;',
  '      vec3 seg = np - pos;',
  '      float tc = clamp(-dot(pos, seg) / max(1e-4, dot(seg, seg)), 0.0, 1.0);',
  '      if (length(pos + seg * tc) < 1.02 || (bimp < 2.6 && r < 6.0)) { trans = 0.0; caught = true; break; }',
  '      if (prevY * np.y < 0.0) {',
  '        float fr = prevY / (prevY - np.y);',
  '        vec3 cp = mix(pos, np, fr);',
  '        float rr = length(cp.xz);',
  '        if (rr > 2.15 && rr < 15.5) {',
  '          float phi = atan(cp.z, cp.x);',
  '          float om = 1.0 / pow(rr, 1.5);',
  '          float a = phi + om * uT * 26.0;',
  '          float n1 = fbm(vec2(a * 0.5 + 2.0, log(rr) * 12.0));',
  '          float n2 = fbm(vec2(a * 1.1 - 1.0, log(rr) * 25.0 + 7.0));',
  '          float ridge = (1.0 - abs(2.0 * n1 - 1.0)) * 0.8 + (1.0 - abs(2.0 * n2 - 1.0)) * 0.3;',
  '          float fil = pow(clamp(ridge - 0.16, 0.0, 1.0), 2.3) * 2.5 + 0.22;',
  '          float edge = smoothstep(2.15, 3.4, rr) * (1.0 - smoothstep(7.0, 15.5, rr));',
  '          float dens = edge * fil;',
  '          float tt = clamp((rr - 2.2) / 7.5, 0.0, 1.0);',
  '          vec3 c = mix(vec3(1.0, 0.99, 0.975), vec3(0.66, 0.4, 0.18), pow(tt, 1.05));',
  '          vec3 vel = normalize(cross(vec3(0.0, 1.0, 0.0), cp)) * (0.46 / sqrt(rr / 3.0));',
  '          float dop = 1.0 / max(0.25, 1.0 - dot(vel, -nd));',
  '          float beam = clamp(pow(dop, 3.1), 0.12, 7.0);',
  '          float bright = 1.7 / pow(rr / 2.6, 2.1);',
  '          float burst = 1.0 + uFlare * 3.2 * smoothstep(0.35, 1.0, cos(phi - uFlareA)) * (1.0 - smoothstep(3.0, 7.5, rr));',
  '          float budget = 1.0 - smoothstep(0.92, 1.0, float(i) / uSteps);',
  '          col += c * dens * bright * beam * burst * trans * budget * uGlow;',
  '          trans *= exp(-dens * uDense * 2.3);',
  '        }',
  '      }',
  '      prevY = np.y; pos = np; dir = nd; outDir = nd;',
  '    }',
  '  }',
  '  if (!caught) col += stars(normalize(outDir)) * trans * uStars * (0.25 + 0.75 * smoothstep(2.6, 5.5, bimp));',
  '  float bIn = max(0.0, 2.605 - bimp), bOut = max(0.0, bimp - 2.605);',
  '  float ring = exp(-pow(bIn * 42.0, 2.0)) * exp(-pow(bOut * 11.0, 2.0));',
  '  col += vec3(1.0, 0.99, 0.97) * ring * 2.4 * uGlow;',
  '  col += vec3(1.0, 0.96, 0.9) * exp(-pow(bimp - 2.66, 2.0) * 26.0) * 0.24 * uGlow;',
  '  col += vec3(1.0, 0.9, 0.8) * exp(-pow(bimp - 2.9, 2.0) * 0.5) * 0.045 * uGlow;',
  '  col *= 0.6 * (1.0 + uFlash * 1.3);',
  '  vec2 hd = uv - uHot;',
  '  float ana = exp(-abs(hd.y) * 150.0) * exp(-abs(hd.x) * 7.0);',
  '  col += vec3(1.0, 0.94, 0.86) * ana * uHotI * 0.35;',
  '  col = (col * (2.51 * col + 0.03)) / (col * (2.43 * col + 0.59) + 0.14);',
  '  col = clamp((col - 0.5) * 1.07 + 0.5, 0.0, 1.0);',
  '  float vg = 1.0 - 0.72 * pow(clamp(length(uv * vec2(uRes.x / uRes.y, 1.0)) * 0.95, 0.0, 1.0), 1.9);',
  '  col *= vg;',
  '  col += (hash(gl_FragCoord.xy + fract(uT) * vec2(37.0, 71.0)) - 0.5) * uGrain * 0.055;',
  '  gl_FragColor = vec4(max(col, 0.0), 1.0);',
  '}',
].join('\n')

export const UNIFORM_NAMES = [
  'uRes',
  'uMouse',
  'uHot',
  'uT',
  'uAz',
  'uEl',
  'uZoom',
  'uGlow',
  'uGrain',
  'uDense',
  'uFlash',
  'uSteps',
  'uFlare',
  'uFlareA',
  'uHotI',
  'uStars',
] as const

/** Claude Design editor defaults */
export const PROPS = {
  diskGlow: 1.8,
  diskDensity: 1,
  starfield: 1.6,
  anamorphic: 0.45,
  grain: 0.12,
} as const

export type Part = {
  term: string
  cam: { az: number; el: number; z: number }
  w?: [number, number, number]
  s?: [number, number]
  hot?: boolean
}

export const PARTS: Part[] = [
  { term: 'event horizon', cam: { az: 0.5, el: 0.42, z: 0.74 }, w: [0, 0, 0] },
  { term: 'photon ring', cam: { az: 0.62, el: 0.3, z: 0.64 }, s: [0.0, -1.02] },
  { term: 'isco / inner edge', cam: { az: 0.3, el: 0.52, z: 0.7 }, w: [2.68, 0, -1.46] },
  { term: 'accretion disk', cam: { az: 0.85, el: 0.56, z: 1.0 }, w: [-4.34, 0, 4.84] },
  { term: 'doppler beaming', cam: { az: 0.45, el: 0.36, z: 0.72 }, hot: true },
  { term: 'lensed halo', cam: { az: 0.55, el: 0.22, z: 0.86 }, s: [0.18, -1.5] },
  { term: 'shadow 2.6 r', cam: { az: 0.5, el: 0.47, z: 1.05 }, s: [-0.72, 0.52] },
  { term: 'ergosphere', cam: { az: 0.38, el: 0.6, z: 0.84 }, s: [0.58, 0.6] },
]

export const CALLOUTS = [
  {
    title: 'Горизонт событий',
    body: 'Граница, за которой скорость убегания превышает скорость света. Всё, что её пересекает, для внешнего наблюдателя перестаёт существовать: сигнал наружу невозможен. Сама граница не излучает и не имеет поверхности — это геометрия, а не объект.',
  },
  {
    title: 'Фотонное кольцо',
    body: 'Тонкая яркая линия на краю тени — свет на последней устойчивой круговой орбите, обогнувший дыру один или несколько раз. Именно из него складывается резкая кромка изображения: внутри неё лучи уже не возвращаются.',
  },
  {
    title: 'Внутренний край диска',
    body: 'Ближе трёх радиусов Шварцшильда устойчивых круговых орбит не существует, поэтому вещество здесь срывается внутрь. Край диска самый горячий: температура растёт к центру, и свечение уходит в белое.',
  },
  {
    title: 'Аккреционный диск',
    body: 'Газ, стянутый гравитацией в тонкий вращающийся слой. Трение между слоями с разной угловой скоростью разогревает его до тысяч кельвинов — это и есть источник всего света в кадре. Скорость падает как корень из радиуса, поэтому внутренние части обгоняют внешние.',
  },
  {
    title: 'Доплеровское пятно',
    body: 'Сторона диска, движущаяся к наблюдателю, ярче удаляющейся в несколько раз: релятивистский бимминг собирает излучение в направлении движения. Асимметрию не выравнивают — она показывает, куда вращается диск.',
  },
  {
    title: 'Линзированное гало',
    body: 'Дальняя половина диска не исчезает за тенью: гравитация загибает её лучи и поднимает изображение над горизонтом и под ним. Диск виден дважды — как полоса в плоскости и как дуга, обнимающая тень.',
  },
  {
    title: 'Тень',
    body: 'Тёмный круг заметно больше самого горизонта: его радиус около 2.6 радиуса Шварцшильда. Это область, откуда к наблюдателю не приходит ни один луч, потому что все они захвачены. Именно тень, а не горизонт, фотографируют телескопы.',
  },
  {
    title: 'Эргосфера',
    body: 'У вращающейся дыры вокруг горизонта есть слой, где пространство увлекается вращением настолько, что покоиться относительно далёких звёзд невозможно. Тело может оставаться снаружи, но обязано вращаться вместе с дырой.',
  },
] as const
